version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-18-214-119-135.compute-1.amazonaws.com
            port: '5432'
            database: dcc0a6mgbo2bsg
            ssl: true
            user: bqggxlozmazotp
            password: df840af2ad4f05234a05edf07aa83e5ad8c86302a2824884419dc6490b44addd
            migrations: true